@echo off
echo Starting deployment...
echo Running Maven build...
mvn clean package
echo Copying the .war file to Tomcat webapps...
copy /y C:\Users\saiki\Desktop\CSP-584-Assignments\Assignment-1\smarthomes\target\smarthomes.war C:\Users\saiki\Desktop\CSP-584-Assignments\Assignment-1\apache-tomcat-10.1.28\webapps
echo Deployment completed successfully.
pause
