import React from "react";
import { Helmet } from "react-helmet";
import PropTypes from 'prop-types';
import "./globals.css"; // Import your global styles

// Layout component
export default function Layout({ children }) {

  return (
    <div>
      {/* Manage page metadata with Helmet */}
      <Helmet>
        <html lang="en" />
        <title>Smart Homes</title>
        <meta name="description" content="Generated by create react app" />
      </Helmet>
      {/* Main body content */}
      {children}
    </div>
  );
}

// PropTypes validation
Layout.propTypes = {
  children: PropTypes.node.isRequired,
};
